// <auto-generated />
namespace dbdit.DAL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UserProfile_Email : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserProfile_Email));
        
        string IMigrationMetadata.Id
        {
            get { return "201211201332017_UserProfile_Email"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
